// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
// Dòng này báo hiệu file này được tự động tạo bởi công cụ EF Core Power Tools, không nên chỉnh sửa thủ công

#nullable disable
// Tắt tính năng nullable reference types cho toàn bộ file này

using System; // Import namespace System để sử dụng các kiểu dữ liệu cơ bản
using System.Collections.Generic; // Import để sử dụng các collection như List, Dictionary
using Microsoft.EntityFrameworkCore; // Import Entity Framework Core để làm việc với database

namespace MyAPI.Repositories.Entities; // Định nghĩa namespace cho các entity classes

// Định nghĩa class MyAPIContext kế thừa từ DbContext của Entity Framework
// DbContext là class chính để tương tác với database
public partial class MyAPIContext : DbContext
{
    // Constructor của MyAPIContext - được gọi khi tạo instance của class này
    // DbContextOptions<MyAPIContext> chứa các cấu hình kết nối database (connection string, provider, etc.)
    public MyAPIContext(DbContextOptions<MyAPIContext> options)
        : base(options) // Gọi constructor của class cha (DbContext) và truyền options vào
    {
    }

    // Định nghĩa DbSet cho bảng Schedule trong database
    // DbSet đại diện cho một bảng trong database, cho phép thực hiện CRUD operations
    public virtual DbSet<Schedule> Schedules { get; set; }

    // Định nghĩa DbSet cho bảng Student trong database
    // virtual cho phép override trong các class con nếu cần
    public virtual DbSet<Student> Students { get; set; }

    // Override method OnModelCreating để cấu hình model mapping với database
    // Method này được gọi khi Entity Framework tạo model từ database
    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        // Cấu hình entity Schedule
        modelBuilder.Entity<Schedule>(entity =>
        {
            // Định nghĩa primary key cho bảng Schedule là trường Id
            // HasName("PK__schedule__3213E83F769E9DDE") là tên constraint trong database
            entity.HasKey(e => e.Id).HasName("PK__schedule__3213E83F769E9DDE");

            // Cấu hình foreign key relationship giữa Schedule và Student
            // Schedule có một Student (MssvNavigation) và Student có nhiều Schedule (Schedules)
            // HasConstraintName định nghĩa tên foreign key constraint trong database
            entity.HasOne(d => d.MssvNavigation).WithMany(p => p.Schedules).HasConstraintName("FK__schedule__mssv__267ABA7A");
        });

        // Cấu hình entity Student
        modelBuilder.Entity<Student>(entity =>
        {
            // Định nghĩa primary key cho bảng Student là trường Mssv
            // HasName("PK__student__763F1CDDAE3607C2") là tên constraint trong database
            entity.HasKey(e => e.Mssv).HasName("PK__student__763F1CDDAE3607C2");
        });

        // Gọi partial method OnModelCreatingPartial nếu có implementation
        // Partial method cho phép thêm cấu hình model ở file khác
        OnModelCreatingPartial(modelBuilder);
    }

    // Định nghĩa partial method - có thể được implement ở file khác
    // Cho phép mở rộng cấu hình model mà không cần chỉnh sửa file auto-generated
    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}