// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace MyAPI.Repositories.Entities;

public partial class MyAPIContext : DbContext
{
    public MyAPIContext(DbContextOptions<MyAPIContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Schedule> Schedules { get; set; }

    public virtual DbSet<Student> Students { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Schedule>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__schedule__3213E83F769E9DDE");

            entity.HasOne(d => d.MssvNavigation).WithMany(p => p.Schedules).HasConstraintName("FK__schedule__mssv__267ABA7A");
        });

        modelBuilder.Entity<Student>(entity =>
        {
            entity.HasKey(e => e.Mssv).HasName("PK__student__763F1CDDAE3607C2");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}