// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace MyAPI.Repositories.Entities;

[Table("schedule")]
public partial class Schedule
{
    [Key]
    [Column("id")]
    public int Id { get; set; }

    [Column("mssv")]
    [StringLength(20)]
    [Unicode(false)]
    public string Mssv { get; set; }

    [Required]
    [Column("class_name")]
    [StringLength(100)]
    public string ClassName { get; set; }

    [Required]
    [Column("subject_name")]
    [StringLength(100)]
    public string SubjectName { get; set; }

    [Column("schedule_time", TypeName = "datetime")]
    public DateTime ScheduleTime { get; set; }

    [ForeignKey("Mssv")]
    [InverseProperty("Schedules")]
    public virtual Student MssvNavigation { get; set; }
}