// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace MyAPI.Repositories.Entities;

[Table("student")]
public partial class Student
{
    [Key]
    [Column("mssv")]
    [StringLength(20)]
    [Unicode(false)]
    public string Mssv { get; set; }

    [Required]
    [Column("name")]
    [StringLength(100)]
    [Unicode(false)]
    public string Name { get; set; }

    [InverseProperty("MssvNavigation")]
    public virtual ICollection<Schedule> Schedules { get; set; } = new List<Schedule>();
}